baseURL = "http://generationzero.org.uk/"
languageCode = "en-gb"
title = "Generation Zero"
#theme = "ananke"
theme = "gzer0"
#paginate = 12

[taxonomies]
  author = "authors"
  category = "categories"
